function T = gfb_transform(obj)
% GFB_TRANSFORM  The attached transform, or an actionable error.
% Author: Diellor Basha, 2026
    if isempty(obj.Transform)
        error('graphfilterbank:noTransform', ...
            ['This bank has no Transform, so it cannot touch a field. Design queries ' ...
             '(graphfilters, framebounds, scales, widths, centerWavenumbers, ...) still ' ...
             'work. Attach one with:\n' ...
             '    gfb.Transform = rheome.graphtransform.eigen(Phi, B, Lambda);\n' ...
             'or build the bank with rheome.graphfilterbank.fromOperator(L).']);
    end
    T = obj.Transform;
end

% Author: Diellor Basha, 2026
