function buildUI(app, visible)
% BUILDUI  The window: a control strip, two readouts, three stacked axes.
%
% ⚠ A CLASSIC FIGURE, NOT A UIFIGURE, AND ON PURPOSE. exportgraphics refuses an unrendered
% uifigure ("Figure must contain graphics"), which is exactly the headless case -- a test, a
% batch script, the figure for a note. A classic figure with uicontrols exports off-screen,
% so `snapshot` works with Visible false and the browser can be driven by a script that never
% opens a window. drawnow does not fix the uifigure case; nothing does.
%
% ⭐ THE MOUSE DRIVES THE SAME PATH AS THE BUTTONS. A listener on the strip's XLim turns the
% axes' own zoom and pan into setWindow calls, so the level-of-detail rule runs for a mouse
% zoom exactly as it does for the zoom button. The Busy flag in refresh keeps the listener
% from re-entering while a redraw is setting those same limits.
%
% Author: Diellor Basha, 2026

    app.Fig = figure('Name', sprintf('recording browser — %s', app.Name), ...
                     'NumberTitle', 'off', 'Color', 'w', 'Units', 'pixels', ...
                     'Position', [60 60 1280 860], 'Visible', i_onoff(visible), ...
                     'KeyPressFcn', @(~, e) app.onKey(e), ...
                     'SizeChangedFcn', @(~,~) i_resized(app));

    names = rheome.recordingbrowser.statsfor(app.Db);
    b = app.Db.bands;
    row = 0.960;  h = 0.030;  sh = 0.926;
    uicontrol(app.Fig, 'Style', 'text', 'Units', 'normalized', 'Position', [0.010 row-0.004 0.030 h], ...
              'String', 'stat', 'BackgroundColor', 'w', 'HorizontalAlignment', 'left');
    app.StatDrop = uicontrol(app.Fig, 'Style', 'popupmenu', 'Units', 'normalized', ...
              'Position', [0.042 row 0.115 h], 'String', cellstr(names), ...
              'Value', max(find(names == string(app.Stat), 1), 1), ...
              'Callback', @(s, ~) app.setStat(s.String{s.Value}));

    uicontrol(app.Fig, 'Style', 'text', 'Units', 'normalized', 'Position', [0.165 row-0.004 0.032 h], ...
              'String', 'band', 'BackgroundColor', 'w', 'HorizontalAlignment', 'left');
    if isempty(b)
        app.BandDrop = uicontrol(app.Fig, 'Style', 'popupmenu', 'Units', 'normalized', ...
              'Position', [0.198 row 0.110 h], 'String', {'(no bands)'}, 'Value', 1, 'Enable', 'off');
    else
        app.BandDrop = uicontrol(app.Fig, 'Style', 'popupmenu', 'Units', 'normalized', ...
              'Position', [0.198 row 0.110 h], 'String', i_bandnames(b), ...
              'Value', find(b.j == app.Band, 1), ...
              'Callback', @(s, ~) app.setBand(b.j(s.Value)));
    end

    uicontrol(app.Fig, 'Style', 'text', 'Units', 'normalized', 'Position', [0.316 row-0.004 0.030 h], ...
              'String', 'unit', 'BackgroundColor', 'w', 'HorizontalAlignment', 'left');
    app.UnitDrop = uicontrol(app.Fig, 'Style', 'popupmenu', 'Units', 'normalized', ...
              'Position', [0.348 row 0.140 h], 'String', {'-'}, 'Value', 1, ...
              'Callback', @(s, ~) app.setUnit(app.UnitIds_(s.Value)));

    app.ViewDrop = uicontrol(app.Fig, 'Style', 'popupmenu', 'Units', 'normalized', ...
              'Position', [0.496 row 0.078 h], 'String', {'channels', 'detail'}, ...
              'Value', 1 + strcmp(app.View, 'detail'), ...
              'Callback', @(s, ~) app.setView(s.String{s.Value}));

    app.ScopeDrop = uicontrol(app.Fig, 'Style', 'popupmenu', 'Units', 'normalized', ...
              'Position', [0.578 row 0.072 h], 'String', {'channel', 'group'}, ...
              'Value', 1 + strcmp(app.Scope, 'group'), ...
              'Callback', @(s, ~) app.setScope(s.String{s.Value}));

    app.AutoBox = uicontrol(app.Fig, 'Style', 'checkbox', 'Units', 'normalized', ...
              'Position', [0.654 row 0.048 h], 'String', 'auto', 'BackgroundColor', 'w', ...
              'Value', app.Auto, 'TooltipString', 'level from the window (a)', ...
              'Callback', @(s, ~) app.setAuto(s.Value));
    app.EnvBox = uicontrol(app.Fig, 'Style', 'checkbox', 'Units', 'normalized', ...
              'Position', [0.702 row 0.046 h], 'String', 'env', 'BackgroundColor', 'w', ...
              'Value', app.Envelope, 'TooltipString', 'min/max envelope (e)', ...
              'Callback', @(s, ~) app.setEnvelope(s.Value));
    uicontrol(app.Fig, 'Style', 'text', 'Units', 'normalized', 'Position', [0.750 row-0.004 0.026 h], ...
              'String', 'lvl', 'BackgroundColor', 'w', 'HorizontalAlignment', 'left');
    app.LevelSpin = uicontrol(app.Fig, 'Style', 'popupmenu', 'Units', 'normalized', ...
              'Position', [0.776 row 0.062 h], 'String', {'-'}, 'Value', 1, ...
              'Callback', @(s, ~) app.setLevel(app.LevelIds_(min(s.Value, numel(app.LevelIds_)))));

    bx = [0.842 0.872 0.902 0.932 0.962 0.842 0.892];    % pan, pan, zoom, zoom, all | load, save
    row2 = row - 0.034;                                  % load and save sit on the second row
    uicontrol(app.Fig, 'Style', 'pushbutton', 'Units', 'normalized', 'Position', [bx(1) row 0.032 h], ...
              'String', '<', 'TooltipString', 'pan earlier', 'Callback', @(~,~) app.panBy(-0.25));
    uicontrol(app.Fig, 'Style', 'pushbutton', 'Units', 'normalized', 'Position', [bx(2) row 0.032 h], ...
              'String', '>', 'TooltipString', 'pan later', 'Callback', @(~,~) app.panBy(+0.25));
    uicontrol(app.Fig, 'Style', 'pushbutton', 'Units', 'normalized', 'Position', [bx(3) row 0.032 h], ...
              'String', '+', 'TooltipString', 'zoom in', 'Callback', @(~,~) app.zoomBy(0.5));
    uicontrol(app.Fig, 'Style', 'pushbutton', 'Units', 'normalized', 'Position', [bx(4) row 0.032 h], ...
              'String', '-', 'TooltipString', 'zoom out', 'Callback', @(~,~) app.zoomBy(2));
    uicontrol(app.Fig, 'Style', 'pushbutton', 'Units', 'normalized', 'Position', [bx(5) row 0.032 h], ...
              'String', 'all', 'TooltipString', 'the whole record', 'Callback', @(~,~) app.fullExtent());
    app.LoadBtn = uicontrol(app.Fig, 'Style', 'pushbutton', 'Units', 'normalized', ...
              'Position', [bx(6) row2 0.048 h], 'String', 'load', ...
              'TooltipString', 'read the raw samples of this window (l)', ...
              'Callback', @(~,~) app.loadRaw());
    uicontrol(app.Fig, 'Style', 'pushbutton', 'Units', 'normalized', 'Position', [bx(7) row2 0.048 h], ...
              'String', 'save', 'TooltipString', 'export this view', 'Callback', @(~,~) app.snapshot());

    % the header: which file this is a picture of, and the matrix behind it
    app.FileLbl = uicontrol(app.Fig, 'Style', 'text', 'Units', 'normalized', ...
              'Position', [0.008 sh+0.022 0.820 0.022], 'String', '', 'BackgroundColor', 'w', ...
              'ForegroundColor', [0.10 0.10 0.10], 'HorizontalAlignment', 'left', 'FontWeight', 'bold');

    % the channel list: multi-select, and the stack follows it
    app.ChanList = uicontrol(app.Fig, 'Style', 'listbox', 'Units', 'normalized', ...
              'Position', [0.008 0.065 0.095 0.810], 'String', {'-'}, 'Min', 0, 'Max', 2, ...
              'Value', 1, 'FontSize', 8, ...
              'Callback', @(s, ~) i_pick(app, s));

    % two readouts on one line: what is on screen (left), and what just happened (right)
    % the readout is two lines: the window and level, then the band's row of the ladder
    app.LevelLbl = uicontrol(app.Fig, 'Style', 'text', 'Units', 'normalized', ...
              'Position', [0.008 sh-0.026 0.700 0.046], 'String', '', 'BackgroundColor', 'w', ...
              'ForegroundColor', [0.15 0.15 0.15], 'HorizontalAlignment', 'left', 'FontSize', 9);
    app.StatusLbl = uicontrol(app.Fig, 'Style', 'text', 'Units', 'normalized', ...
              'Position', [0.715 sh 0.275 0.024], 'String', '', 'BackgroundColor', 'w', ...
              'ForegroundColor', [0.40 0.40 0.40], 'HorizontalAlignment', 'right');

    app.StatAx = axes(app.Fig, 'Position', [0.068 0.630 0.870 0.255]);
    app.TileAx = axes(app.Fig, 'Position', [0.068 0.330 0.870 0.265]);
    app.RawAx  = axes(app.Fig, 'Position', [0.068 0.065 0.870 0.205]);

    app.syncUnits();
    app.syncLevels();
    app.layout();
    addlistener(app.TileAx, 'XLim', 'PostSet', @(~,~) i_onlim(app));
end

% A mouse zoom or pan on the strip changes XLim; anything that is not just the redraw putting
% the window back becomes a setWindow, so the level follows the mouse.
function i_onlim(app)
    if ~isvalid(app) || app.Busy || isempty(app.TileAx) || ~isvalid(app.TileAx), return; end
    x = app.TileAx.XLim;
    if abs(x(1) - app.Window(1)) < 1e-9 && abs(x(2) - app.Window(2)) < 1e-9, return; end
    app.setWindow(x(1), x(2));
end

% A wider window is more pixels, and with the default budget that is more detail. Guarded by
% Busy, since drawing sets axis limits which can fire this again.
function i_resized(app)
    if ~isvalid(app) || app.Busy || isempty(app.StatAx) || ~isvalid(app.StatAx), return; end
    if isnumeric(app.Budget), return; end                % a fixed budget ignores the resize
    app.refresh();
end

% The list is the selection: the stack draws exactly what is highlighted.
function i_pick(app, h)
    v = get(h, 'Value');
    if isempty(v), return; end
    app.setUnits(app.UnitIds_(v));
end

function s = i_bandnames(b)
    s = cell(height(b), 1);
    for i = 1:height(b)
        s{i} = sprintf('%d: %.3g-%.3g Hz', b.j(i), b.fLo(i), b.fHi(i));
    end
end

function v = i_onoff(tf)
    if tf, v = 'on'; else, v = 'off'; end
end
% Author: Diellor Basha, 2026
