function S = schema()
% SELECT.SCHEMA  The relational schema the tile store already is: relations, columns, keys.
%
%   S = rheome.select.schema()     struct array, one element per relation:
%       .name .columns {1 x n} .types {1 x n} (Postgres) .key {1 x m} .foreign {struct: column -> relation}
%
% Design: docs/2026-09-22-select-design.md §2; the position pyramid (sensor_group and the
% feature_group relations, internal nodes only -- leaves are the channel rows) is §2b. rheome.select.ddl prints it as Postgres DDL;
% rheome.select.rows materialises any relation from a MATLAB store.
%
% ⭐ TWO MATRICES OVER THE SAME NODES, and `.kind` says which is which.
%   'mergeable'  dense, one row per (unit, tile), a parent exactly the merge of its
%                children: the moments, computed once at the finest level and rolled up.
%                Bounds hold, so a query prunes by descending (rheome.select.frames).
%   'note'       sparse, one row per (node, kind), whatever was measured where it was
%                measured: labels and measurements. NOTHING here merges -- a value on a
%                node says nothing about its parent -- so these are scanned or indexed,
%                never descended, and values at two levels are two observations, not one.
%   'dimension'  the axes themselves: recording, channel, band, tile, sensor_group, space_band,
%                cortex_node (rheome.geom.tree, the position pyramid on the far side of the inverse).
% Keeping them in separate relations is the whole discipline: it makes "this number is a
% summary of its children" and "this number was measured here" impossible to confuse.
%
% Author: Diellor Basha, 2026

    rec = struct('name', 'recording', ...
        'columns', {{'recording_id','source','fs','n_samples','duration','units','bank','cfg_hash','release','commit','created'}}, ...
        'types',   {{'text','text','double precision','integer','double precision','text','text','text','text','text','timestamp'}}, ...
        'key', {{'recording_id'}}, 'foreign', struct(), 'kind', 'dimension');
    chan = struct('name', 'channel', ...
        'columns', {{'recording_id','channel_id','name','type','store_row'}}, ...
        'types',   {{'text','integer','text','text','integer'}}, ...
        'key', {{'recording_id','channel_id'}}, 'foreign', struct('recording_id', 'recording'), 'kind', 'dimension');
    band = struct('name', 'band', ...
        'columns', {{'recording_id','band_id','kind','f_lo','f_hi','f_center','f_extent','t_support','natural_level','partial'}}, ...
        'types',   {{'text','integer','text','double precision','double precision','double precision','double precision','double precision','integer','boolean'}}, ...
        'key', {{'recording_id','band_id'}}, 'foreign', struct('recording_id', 'recording'), 'kind', 'dimension');
    tile = struct('name', 'tile', ...
        'columns', {{'recording_id','level','k','t_center','t_extent','n'}}, ...
        'types',   {{'text','integer','integer','double precision','double precision','integer'}}, ...
        'key', {{'recording_id','level','k'}}, 'foreign', struct('recording_id', 'recording'), 'kind', 'dimension');
    cone = struct('name', 'tile_cone', ...
        'columns', {{'recording_id','level','k','band_id','n_coi'}}, ...
        'types',   {{'text','integer','integer','integer','integer'}}, ...
        'key', {{'recording_id','level','k','band_id'}}, 'foreign', struct('recording_id', 'recording', 'band_id', 'band', 'level_k', 'tile'), 'kind', 'mergeable');
    feat = struct('name', 'feature', ...
        'columns', {{'recording_id','channel_id','level','k','sum_x','sum_x2','abs_max','min','max'}}, ...
        'types',   {{'text','integer','integer','integer','double precision','double precision','real','real','real'}}, ...
        'key', {{'recording_id','channel_id','level','k'}}, 'foreign', struct('recording_id', 'recording', 'channel_id', 'channel', 'level_k', 'tile'), 'kind', 'mergeable');
    fband = struct('name', 'feature_band', ...
        'columns', {{'recording_id','channel_id','level','k','band_id','energy','env_max'}}, ...
        'types',   {{'text','integer','integer','integer','integer','double precision','real'}}, ...
        'key', {{'recording_id','channel_id','level','k','band_id'}}, 'foreign', struct('recording_id', 'recording', 'channel_id', 'channel', 'band_id', 'band', 'level_k', 'tile'), 'kind', 'mergeable');
    label = struct('name', 'label', ...
        'columns', {{'label_id','recording_id','channel_id','level','k','band_id','kind','value','source','txn_id'}}, ...
        'types',   {{'bigserial','text','integer','integer','integer','integer','text','double precision','text','bigint'}}, ...
        'key', {{'label_id'}}, 'foreign', struct('recording_id', 'recording', 'txn_id', 'txn'), 'kind', 'note');
    txn = struct('name', 'txn', ...
        'columns', {{'txn_id','recording_id','kind','count','content_hash','author','created'}}, ...
        'types',   {{'bigserial','text','text','integer','text','text','timestamp'}}, ...
        'key', {{'txn_id'}}, 'foreign', struct('recording_id', 'recording'), 'kind', 'note');
    grp = struct('name', 'sensor_group', ...
        'columns', {{'recording_id','group_id','parent_id','depth','n_sensors','is_leaf','channel_id','diameter','centroid_x','centroid_y','centroid_z'}}, ...
        'types',   {{'text','integer','integer','integer','integer','boolean','integer','double precision','double precision','double precision','double precision'}}, ...
        'key', {{'recording_id','group_id'}}, 'foreign', struct('recording_id', 'recording'), 'kind', 'dimension');
    fgrp = struct('name', 'feature_group', ...
        'columns', {{'recording_id','group_id','level','k','sum_x','sum_x2','abs_max','min','max'}}, ...
        'types',   {{'text','integer','integer','integer','double precision','double precision','real','real','real'}}, ...
        'key', {{'recording_id','group_id','level','k'}}, 'foreign', struct('recording_id', 'recording', 'group_id', 'sensor_group', 'level_k', 'tile'), 'kind', 'mergeable');
    fgband = struct('name', 'feature_group_band', ...
        'columns', {{'recording_id','group_id','level','k','band_id','energy','env_max'}}, ...
        'types',   {{'text','integer','integer','integer','integer','double precision','real'}}, ...
        'key', {{'recording_id','group_id','level','k','band_id'}}, 'foreign', struct('recording_id', 'recording', 'group_id', 'sensor_group', 'band_id', 'band', 'level_k', 'tile'), 'kind', 'mergeable');
    sband = struct('name', 'space_band', ...
        'columns', {{'recording_id','sband_id','kind','k_lo','k_hi','k_center','wavelength_lo','wavelength_hi','wavelength_center','n_modes'}}, ...
        'types',   {{'text','integer','text','double precision','double precision','double precision','double precision','double precision','double precision','double precision'}}, ...
        'key', {{'recording_id','sband_id'}}, 'foreign', struct('recording_id', 'recording'), 'kind', 'dimension');
    fspace = struct('name', 'feature_space', ...
        'columns', {{'recording_id','channel_id','level','k','sband_id','energy','env_max'}}, ...
        'types',   {{'text','integer','integer','integer','integer','double precision','real'}}, ...
        'key', {{'recording_id','channel_id','level','k','sband_id'}}, 'foreign', struct('recording_id', 'recording', 'channel_id', 'channel', 'sband_id', 'space_band', 'level_k', 'tile'), 'kind', 'mergeable');
    fgspace = struct('name', 'feature_group_space', ...
        'columns', {{'recording_id','group_id','level','k','sband_id','energy','env_max'}}, ...
        'types',   {{'text','integer','integer','integer','integer','double precision','real'}}, ...
        'key', {{'recording_id','group_id','level','k','sband_id'}}, 'foreign', struct('recording_id', 'recording', 'group_id', 'sensor_group', 'sband_id', 'space_band', 'level_k', 'tile'), 'kind', 'mergeable');
    % ⭐ The cortical position pyramid: the twin of sensor_group on the other side of the inverse.
    % rheome.geom.tree's nodes, so `measure` rows can be addressed with Scope="cortex" and unit_id = node_id.
    % ⚠ wavelength_mm is carried because admissibility is a property of the NODE, not of the
    % measurement: a node at or below 2*r50 = 104 mm cannot support a size or separation claim, and
    % the rows are kept and flagged rather than dropped (they are the control).
    cnode = struct('name', 'cortex_node', ...
        'columns', {{'recording_id','node_id','parent_id','depth','hemi','n_vertices','is_leaf','area','diameter','wavelength_mm','centroid_x','centroid_y','centroid_z'}}, ...
        'types',   {{'text','integer','integer','integer','text','integer','boolean','double precision','double precision','double precision','double precision','double precision','double precision'}}, ...
        'key', {{'recording_id','node_id','hemi'}}, 'foreign', struct('recording_id', 'recording'), 'kind', 'dimension');

    % ⭐ The cortical features: the mergeable twin of feature_group on the source side, over
    % cortex_node's whole-cortex heap ids (rheome.geom.cortexnodes). SUMS only, so a node is the sum of its two
    % children and a tile of its two halves; occupancy = on_area_s / area_s at read time. Written by
    % rheome.flow.cortexfeatures into <store>__cortex.mat (rheome.select.cortexfile), never into the store.
    % ⚠ cband_id is a member of the CORTICAL spatial bank (logitersine on the LBO), not space_band's
    % sensor-array band; the two share no ids, hence the different name.
    fcort = struct('name', 'feature_cortex', ...
        'columns', {{'recording_id','node_id','level','k','band_id','area_s','on_area_s','energy'}}, ...
        'types',   {{'text','integer','integer','integer','integer','double precision','double precision','double precision'}}, ...
        'key', {{'recording_id','node_id','level','k','band_id'}}, 'foreign', struct('recording_id', 'recording', 'band_id', 'band', 'level_k', 'tile'), 'kind', 'mergeable');
    fcspace = struct('name', 'feature_cortex_space', ...
        'columns', {{'recording_id','node_id','level','k','band_id','cband_id','energy'}}, ...
        'types',   {{'text','integer','integer','integer','integer','integer','double precision'}}, ...
        'key', {{'recording_id','node_id','level','k','band_id','cband_id'}}, 'foreign', struct('recording_id', 'recording', 'band_id', 'band', 'level_k', 'tile'), 'kind', 'mergeable');

    % The measurement matrix: the second bookkeeping matrix over the same nodes. A row is
    % one number of one kind, measured at one node, on a channel or a sensor-tree node
    % (scope + unit_id, which `label` cannot address) and optionally in one band. Sparse,
    % heterogeneous and NON-MERGING by construction; written in the same transactions.
    meas = struct('name', 'measure', ...
        'columns', {{'measure_id','recording_id','scope','unit_id','level','k','band_id','kind','value','source','txn_id'}}, ...
        'types',   {{'bigserial','text','text','integer','integer','integer','integer','text','double precision','text','bigint'}}, ...
        'key', {{'measure_id'}}, 'foreign', struct('recording_id', 'recording', 'txn_id', 'txn'), 'kind', 'note');
    S = [rec, chan, band, tile, cone, feat, fband, grp, fgrp, fgband, sband, fspace, fgspace, cnode, fcort, fcspace, label, meas, txn];
end
% Author: Diellor Basha, 2026
