classdef tSensorGenerate < matlab.unittest.TestCase
% Patterns generated by evolving a delta with a dynamical family, rather than by
% hand-written trigonometry. The family sets the dynamics; the seed sets where.

    methods (Static)
        function [G, M] = fixture()
            persistent Gc Mc
            if isempty(Gc)
                w = warning('off', 'sensors:calibrate:narrowFitWindow');
                c = onCleanup(@() warning(w));
                Gc = rheome.sensors.graph(rheome.sensors.grid('utah'));
                Mc = rheome.sensors.modes(Gc);
            end
            G = Gc;  M = Mc;
        end
        function r = radius(G, u, seed)
            % Energy-weighted mean distance from the seed. The measure of "how far has
            % this spread", in metres.
            d = vecnorm(G.Vertices - G.Vertices(seed,:), 2, 2);
            e = abs(u).^2;  s = sum(e);
            if s <= 0, r = 0; else, r = sum(e .* d) / s; end
        end
    end

    methods (Test)

        function aDeltaEvolvedByTheWaveFamilyExpands(tc)
            % The defining behaviour: rheome.filters.wave says a delta launches an expanding
            % wavefront, so the energy radius must GROW. A pattern that stays put is a
            % dead generator, which is exactly what a wrong parameter silently produces.
            [G, M] = tSensorGenerate.fixture();
            seed = 45;
            U = rheome.sensors.generate(G, 'wave', 'Vertex', seed, 'Modes', M, ...
                                 'SamplingFrequency', 200, 'SignalLength', 128, ...
                                 'Args', {30});
            r0 = tSensorGenerate.radius(G, U(:,1),  seed);
            r1 = tSensorGenerate.radius(G, U(:,16), seed);
            r2 = tSensorGenerate.radius(G, U(:,48), seed);
            tc.verifyEqual(r0, 0, 'AbsTol', 1e-12, 'a delta starts on its seed');
            tc.verifyGreaterThan(r1, r0);
            tc.verifyGreaterThan(r2, r1);
        end

        function bothNativeAxesAreHandled(tc)
            % 'ts' families are (lambda x time) propagators; 'js' families are
            % (lambda x omega) joint kernels. generate picks the axis from the family so
            % the caller does not have to know which is which.
            [G, M] = tSensorGenerate.fixture();
            for f = {'wave', 'diffusion', 'travwave', 'resonator'}
                U = rheome.sensors.generate(G, f{1}, 'Vertex', 45, 'Modes', M, ...
                                     'SamplingFrequency', 200, 'SignalLength', 128);
                tc.verifySize(U, [G.nV, 128], sprintf('family %s', f{1}));
                tc.verifyTrue(all(isfinite(U(:))), sprintf('family %s is finite', f{1}));
            end
        end

        function theGeneratedPatternIsExactlyFiltersImpulse(tc)
            % generate ADAPTS rheome.filters.impulse to a sensor graph. It must never become a
            % second implementation of it.
            [G, M] = tSensorGenerate.fixture();
            fs = 200;  N = 128;  t = (0:N-1)/fs;  seed = 45;
            [U, info] = rheome.sensors.generate(G, 'wave', 'Vertex', seed, 'Modes', M, ...
                                         'SamplingFrequency', fs, 'SignalLength', N, ...
                                         'Args', {30});
            basis = struct('Phi',M.Phi, 'Lambda',M.Lambda, 'Mass',speye(G.nV), 'nV',G.nV);
            ref = rheome.filters.impulse(basis, seed, rheome.filters.wave(M.Lambda, t, 30, M.Lmax), 'ts');
            tc.verifyEqual(U, ref, 'AbsTol', 1e-12);
            tc.verifyEqual(info.Domain, 'ts');
        end

        function infoReportsTheParametersActuallyUsed(tc)
            % ⚠ THE FAMILY DEFAULTS ARE IN FAMILY UNITS, NOT ARRAY UNITS, and are usually
            % wrong for a given array. Reporting them is what makes that visible instead
            % of leaving a caller to wonder why nothing moved.
            [G, M] = tSensorGenerate.fixture();
            [~, info] = rheome.sensors.generate(G, 'wave', 'Vertex', 45, 'Modes', M, ...
                                         'SamplingFrequency', 200, 'SignalLength', 128, ...
                                         'Args', {30});
            tc.verifyEqual(info.Family, 'wave');
            tc.verifyEqual(info.Vertex, 45);
            tc.verifyEqual(info.Args{1}, 30);
            tc.verifyNumElements(info.Time, 128);
        end

        function anUnknownFamilyIsRefusedByName(tc)
            G = tSensorGenerate.fixture();
            tc.verifyError(@() rheome.sensors.generate(G, 'sombrero'), 'sensors:generate:family');
        end

        function aSeedOutsideTheArrayIsRefused(tc)
            [G, M] = tSensorGenerate.fixture();
            tc.verifyError(@() rheome.sensors.generate(G, 'wave', 'Vertex', G.nV+1, 'Modes', M), ...
                'sensors:generate:vertex');
        end

        function theDemoMakesNoSourceClaim(tc)
            % Spec section 1.1: sensor space only.
            src = fileread(which('rheome.sensors.generate'));
            tc.verifyEmpty(regexpi(src, 'leadfield|cortex|cortical|dipole|anatom', 'once'));
        end

    end
end

% Author: Diellor Basha, 2026
