function ax = axes(obj)
% AXES  The axes this bank lives on, as a plain struct.
%
%   ax = axes(jfb)
%
% Carries BOTH axes and the two conventions that make representations combinable at all.
% Check pairs with iscompatible before composing, comparing or reconstructing across two
% analyses -- especially across BANDS, since a per-band run truncates to its own bins.
%
% See also: iscompatible
%
% Author: Diellor Basha, 2026

    lam = obj.Lambda;
    ax = struct('lambda',   lam, ...
                'k',        sqrt(lam), ...
                'f',        obj.Frequencies, ...
                'omega',    obj.Omega, ...
                'fs',       obj.SamplingFrequency, ...
                'nfft',     obj.SignalLength, ...
                'nOmega',   obj.NumOmega, ...
                'df',       obj.Df, ...
                'half',     obj.Half, ...
                'boundary', obj.Boundary);
end

% Author: Diellor Basha, 2026
