function T = totable(obj, out)
% TOTABLE  The long form: one row per (window, band, scale, ROI).
%
%   T = totable(fe, out)
%
% The N-D array in `out` is compact and fast to slice; this is the form MATLAB's statistics
% tooling wants -- groupsummary, grpstats, fitlm all take it directly. Band, ROI and
% hemisphere are CATEGORICAL so grouping works without string comparison.
%
% ⚠ THE NORMALISERS RIDE ALONG as columns rather than being applied. `density` is provided
% because it is almost always the right comparison (energy per sample per unit area), but
% `energy`, `nSamples`, `roiArea` and `totalEnergy` are all present so any other choice
% remains open.
%
% Author: Diellor Basha, 2026

    [nW, nB, nS, nR] = size(out.Energy);
    [iw, ib, ig, ir] = ndgrid(1:nW, 1:nB, 1:nS, 1:nR);
    iw = iw(:);  ib = ib(:);  ig = ig(:);  ir = ir(:);

    lin = sub2ind([nW nB nS nR], iw, ib, ig, ir);
    linWB = sub2ind([nW nB], iw, ib);
    linWBS = sub2ind([nW nB nS], iw, ib, ig);

    T = table( ...
        iw, ...
        out.tStart(iw), ...
        categorical(out.Bands(ib).'), ...
        out.ScaleMM(ig).', ...
        categorical(out.ROILabel(ir).'), ...
        categorical(out.ROIHemi(ir).'), ...
        out.Energy(lin), ...
        out.Density(lin), ...
        out.ScaleEnergy(linWBS), ...
        out.TotalEnergy(linWB), ...
        out.ROIArea(ir).', ...
        out.WindowSamples(linWB), ...
        repmat(out.PageIndex, numel(iw), 1), ...
        'VariableNames', {'window','tStart','band','scaleMM','roi','hemi', ...
                          'energy','density','scaleEnergy','totalEnergy','roiArea', ...
                          'nSamples','page'});
end

% Author: Diellor Basha, 2026
